version: "3.7"
volumes:
  server-node_modules:
  client-node_modules:
  postgres-data:

services:
  # server
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: reshub-server
    environment:
      - NODE_ENV=development
      - COMMAND=${COMMAND:-serve}
    env_file:
      - reshub-deploy/.env.dev
    image: reshub-server:latest
    ports:
      - 8090:8090
      - 5555:5555 # prisma studio port
    volumes:
      - ./app/server:/app
      - server-node_modules:/app/node_modules
    tty: true
    depends_on:
      - postgresql

  # prd
  production:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    container_name: reshub-server_prd
    environment:
      - NODE_ENV=production
      - COMMAND=${COMMAND:-start}
    env_file:
      - reshub-deploy/.env.production
    image: reshub_prd
    ports:
      - 8091:8090
    depends_on:
      - postgresql

  # client
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    container_name: reshub-client
    environment:
      - COMMAND=${COMMAND:-start}
    env_file:
      - reshub-deploy/.env.dev
    image: reshub-client:latest
    ports:
      - 8080:3000
    volumes:
      - ./app/client:/app
      - client-node_modules:/app/node_modules
    tty: true

  postgresql:
    image: postgres:12
    container_name: reshub-db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - reshub-deploy/.env.dev
