version: "3.7"
volumes:
  server-node_modules:
  client-node_modules:
  db-data:

services:

  # server
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: reshub-server
    environment: 
      - NODE_ENV=development
      - COMMAND=${COMMAND:-serve}
    env_file: 
      - .env.dev
    image: reshub-server
    ports: 
      - 8090:8090
    volumes:
      - ./app/server:/app
      - server-node_modules:/app/node_modules
    tty: true
    depends_on: 
      - db
      - redis
  
  # prd server
  server-prd:
    container_name: reshub-server
    environment: 
      - NODE_ENV=production
      - COMMAND=${COMMAND:-start}
    image: reshub-server_prd
    ports: 
      - 8090:8090
    depends_on: 
      - db
      - redis

  # client
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    container_name: reshub-client
    environment:
      - COMMAND=${COMMAND:-start}
    env_file: 
      - .env.dev
    image: reshub-client
    ports:
      - 8080:3000
    volumes:
      - ./app/client:/app
      - client-node_modules:/app/node_modules
    tty: true

  # db
  db:
    image: mongo:4.2
    container_name: reshub-mongodb
    volumes:
        - db-data:/data/db
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  redis:
    image: redis:alpine
    ports:
      - 6379
    